#!/bin/sh

# start, or restart, caputRecorder.py

PREFIX=$1

EPICS_APP=/net/s100dserv/xorApps/zed/epics/ioc_6_2_1/ioczed
MACROS_PY_DIR=${EPICS_APP}/tmmApp/op/python

output=`perl -s ${EPICS_APP}/release.pl -form=bash ${EPICS_APP}`
eval $output

#echo "CAPUTRECORDER=", $CAPUTRECORDER
CAPUTRECORDER_PY=${CAPUTRECORDER}/caputRecorderApp/op/python/caputRecorder.py

arch=`uname -p`
COMMAND="/APSshare/anaconda/${arch}/bin/python ${CAPUTRECORDER_PY}"
#COMMAND="/APSshare/epd/rh6-x86_64/bin/python ${CAPUTRECORDER_PY}"

export PYTHONPATH=${MACROS_PY_DIR}:$PYTHONPATH
namePrefix=$( echo $PREFIX | sed s/://g )
MACROS_PY=${MACROS_PY_DIR}/"macros_"${namePrefix}.py

export EPICS_CA_MAX_ARRAY_BYTES=10000100

#echo "EPICS_CA_MAX_ARRAY_BYTES=", $EPICS_CA_MAX_ARRAY_BYTES
# start caputRecorder.py
$COMMAND ${PREFIX} ${MACROS_PY}&
