#!/bin/sh
# set path to include EPICS executables
export PATH=$PATH:/APSshare/epics/base-7.0.8/bin/linux-arm
caRepeater&

# ensure that multiple, simultaneous IOCs are not started by this user ID

# petalinux doesn't have pgrep
MY_UID=`id -u`
# petalinux doesn't have epgrep
#IOC_PID="`/usr/bin/pgrep zzz\$ -u ${MY_UID}`"
IOC_PID="`ps | awk '{sub(/.*\//, "", $5)} $5 ~ /zzz/ {print $1}'`"
if [ "" != "${IOC_PID}" ] ; then
  echo "zzz IOC is already running, won't start a new one, PID=${IOC_PID}"
  exit 1
fi

# start the IOC

../../bin/linux-arm/zzz st.cmd
